### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/PulseMonitor#16]
Looks like the login functionality in `chatexchange` is no longer operational.

```
2019-01-08 14:05:40,506:client:Logging in.
Traceback (most recent call last):
  File "./Source/startup.py", line 19, in <module>
    Pulse("PulseMonitor", email, password, rooms=[65945])
  File "/home/ec2-user/PulseMonitor/Source/Pulse.py", line 31, in __init__
    bot = bp.Bot(nick, commands, rooms, [], "stackexchange.com", email, password)
  File "/home/ec2-user/PulseMonitor/hlenv/lib64/python3.6/dist-packages/BotpySE/Bot.py", line 28, in __init__
    super().__init__(host, email, password)
  File "/home/ec2-user/PulseMonitor/hlenv/lib64/python3.6/dist-packages/chatexchange/client.py", line 76, in __init__
    self.login(email, password)
  File "/home/ec2-user/PulseMonitor/hlenv/lib64/python3.6/dist-packages/chatexchange/client.py", line 140, in login
    self._br.login_site(self.host)
  File "/home/ec2-user/PulseMonitor/hlenv/lib64/python3.6/dist-packages/chatexchange/browser.py", line 169, in login_site
    'openid_identifier': 'https://openid.stackexchange.com/'
  File "/home/ec2-user/PulseMonitor/hlenv/lib64/python3.6/dist-packages/chatexchange/browser.py", line 190, in _se_openid_login_with_fkey
    response = self.post(post_url, data, with_chat_root=False)
  File "/home/ec2-user/PulseMonitor/hlenv/lib64/python3.6/dist-packages/chatexchange/browser.py", line 113, in post
    return self._request('post', url, data, headers, with_chat_root)
  File "/home/ec2-user/PulseMonitor/hlenv/lib64/python3.6/dist-packages/chatexchange/browser.py", line 102, in _request
    response.raise_for_status()
  File "/home/ec2-user/PulseMonitor/hlenv/lib64/python3.6/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://stackexchange.com/users/authenticate
```

**Comment by tripleee** [comment]
Experimentally tried replacing `chatexchange` with the version Smoke Detector is using, but no go.

**Comment by double-fault** [comment]
Wait. Is CE not working for all bots or is this a problem just with PM?

**Comment by double-fault** [comment]
(After seeing the Channels post)

@tripleee The changes required for the OpenID shift have been done in CE, so that surely isn't the problem. I originally suspected that the problem was with Botpy, but another bot which uses it seems to be working fine. Could you try booting PM from a different account? That might solve the problem.

**Comment by double-fault** [comment]
Also, what version of CE and Botpy are you running?

**Comment by tripleee** [comment]
```
ec2-user@ip-172-31-224-113 PulseMonitor]$ pip freeze | fgrep -e Botpy -e Chat
BotpySE==0.6.5
ChatExchange==0.0.3
```

**Comment by tripleee** [comment]
I experimentally updated to `ChatExchange==0.0.4` and it's looking better, but it's still not working.

Here I'm running from my laptop;

```
$ sh ./run.PROD
2019-01-09 11:51:39,993:client:Logging in.
Traceback (most recent call last):
  File "./Source/startup.py", line 19, in <module>
    Pulse("PulseMonitor", email, password, rooms=[65945])
  File "/Users/tripleee/charcoal/PulseMonitor/Source/Pulse.py", line 31, in __init__
    bot = bp.Bot(nick, commands, rooms, [], "stackexchange.com", email, password)
  File "/Users/tripleee/charcoal/PulseMonitor/pmenv/lib/python3.5/site-packages/BotpySE/Bot.py", line 28, in __init__
    super().__init__(host, email, password)
  File "/Users/tripleee/charcoal/PulseMonitor/pmenv/lib/python3.5/site-packages/chatexchange/client.py", line 76, in __init__
    self.login(email, password)
  File "/Users/tripleee/charcoal/PulseMonitor/pmenv/lib/python3.5/site-packages/chatexchange/client.py", line 138, in login
    self._br.login_site(self.host, email, password)
  File "/Users/tripleee/charcoal/PulseMonitor/pmenv/lib/python3.5/site-packages/chatexchange/browser.py", line 158, in login_site
    "failed to get `acct` cookie from Stack Exchange OpenID, "
chatexchange.browser.LoginError: failed to get `acct` cookie from Stack Exchange OpenID, check credentials provided for accuracy
```

The same credentials I have in the file work fine for interactive login, verified with copy+paste.

**Comment by double-fault** [comment]
Hmm.. I'll try running PM from my comp today or tomorrow and will try to troubleshoot the issue.

**Comment by tripleee** [comment]
Looks like logging in with MadMoiselle instead of the regular account works fine. Time to divorce PulseMonitor from Thunder?

**Comment by tripleee** [comment]
As a workaround, MadMoiselle is now running the bot in Charcoal Test.

**Comment by double-fault** [comment]
FYI, Thunder isn't running right now. There were some problems with my instance and I just couldn't find the time to reboot it, so another user is running it right now on a different account. That means that the problem couldn't be related to an account being shared between PM and Thunder.

**Comment by tripleee** [comment]
Turned out to be a simple matter of separately have the account join the community on https://meta.stackexchange.com/ in order to be able to log in to rooms which are not linked to another site in the network.

I switched the bot to run on [its own dedicated account](https://graphicdesign.stackexchange.com/users/131636/halflife) now.

**Comment by double-fault** [comment]
Alright, thanks a lot!

**Comment by double-fault** [comment]
Would it make sense to change the bot name to Halflife now that the bot account is named so, so as to avoid confusion?

**Comment by tripleee** [comment]
I have been thinking about that, too. There is already a project named halflife which runs the back-end websocket server that the bot listens to, so this is slightly complicated.

**Comment by tripleee** [comment]
Ref https://github.com/SOBotics/Thunder/issues/12

**Comment by double-fault** [comment]
Then why don't we just rename the bot account to PulseMonitor, like before? If that isn't an option, I'll look into modifying Botpy to allow multiple bot names for command pings; the changes shouldn't be very complicated, but I'm not sure when I'll be able to get to it.

IMHO, keeping the ping name as PulseMonitor but naming the bot account Halflife will be confusing. Keeping both as aliases should work, but that will require some modification.
