### ISSUE TITLE
Redunda pings don't work

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/PulseMonitor#27]
The bot checks in with Redunda when it starts, but after that, I only see "500 server error" in the logs, and pings seem to fail.

**Comment by tripleee** [comment]
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/tripleee/.pyenv/versions/3.7.2/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Users/tripleee/.pyenv/versions/3.7.2/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/tripleee/charcoal/PulseMonitor/pmenv/lib/python3.7/site-packages/BotpySE/BackgroundTask.py", line 20, in call_function
    self.function_callback()
  File "/Users/tripleee/charcoal/PulseMonitor/pmenv/lib/python3.7/site-packages/BotpySE/Redunda.py", line 39, in update
    self._redunda.sendStatusPing()
  File "/Users/tripleee/charcoal/PulseMonitor/pmenv/lib/python3.7/site-packages/pyRedunda/Redunda.py", line 43, in sendStatusPing
    response = request.urlopen(req)
  File "/Users/tripleee/.pyenv/versions/3.7.2/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/tripleee/.pyenv/versions/3.7.2/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Users/tripleee/.pyenv/versions/3.7.2/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Users/tripleee/.pyenv/versions/3.7.2/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/Users/tripleee/.pyenv/versions/3.7.2/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Users/tripleee/.pyenv/versions/3.7.2/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error
```

**Comment by tripleee** [comment]
Seems to have been resolved on the Redunda side somehow?
